### PR TITLE
Updates to match _p branch

### PR DESCRIPTION
**Pull request by mjs513**
Took a shot at updating to want I have - did test with kurts fb sketch and the embedPic sketch  Next up to double check rotatedRect sketch

### CODE REVIEW

**Comment by wwatson4506** [comment]
PR done. I don't have SPI device setup yet but when I do I'll test it out😀

**Comment by mjs513** [comment]
Just as a heads up.  Was playing with my rotated sketch and for some reason the 480x320 mm image does want to work in rotation 1 ??  not sure why other tests work well but no issue with embedPict sketch.  Scratching head on that one

**Comment by wwatson4506** [comment]
I could not get any of the examples in RA8876_t41_p branch to work except
for the ones in the testcases folder. They appear to be setup for SPI
instead of 8080.

**Comment by mjs513** [comment]
Ok something must have got crossed.  I never double checked what was on github for examples.  I pushed the updates.  The are set up for 8080, at least the ones I checked but the lib include name still needs to be changed.  Will work on that soon - diner time

**Comment by wwatson4506** [comment]
I figured something like that happened. It gets real confusing sometimes😄

**Pull request merged**
